# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_de_merde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('label',),
            },
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('question', 'color'), 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='color',
            field=models.CharField(choices=[('0', 'red'), ('1', 'black'), ('2', 'blue')], max_length=1),
        ),
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='app_de_merde.Category'),
            preserve_default=False,
        ),
    ]
